### ISSUE TITLE
Getting compile errors with 3.7.2 using tsc

### ISSUE THREAD

**Issue by hiro5id** [michaelwittig/node-i18n-iso-countries#107]
It works fine on 3.7.1 but 3.7.2 gives following compile errors:

```rm -rf dist && tsc

node_modules/i18n-iso-countries/index.d.ts(11,16): error TS7010: '(Missing)', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/i18n-iso-countries/index.d.ts(11,17): error TS1003: Identifier expected.
node_modules/i18n-iso-countries/index.d.ts(11,24): error TS2552: Cannot find name 'lang'. Did you mean 'langs'?
node_modules/i18n-iso-countries/index.d.ts(11,28): error TS1005: ',' expected.
node_modules/i18n-iso-countries/index.d.ts(11,30): error TS2693: 'string' only refers to a type, but is being used as a value here.
node_modules/i18n-iso-countries/index.d.ts(11,37): error TS1005: ';' expected.
node_modules/i18n-iso-countries/index.d.ts(11,43): error TS1109: Expression expected.```

**Comment by swftvsn** [comment]
Same here..

**Comment by llulani** [comment]
In [#105](https://github.com/michaelwittig/node-i18n-iso-countries/issues/105) they have (re)introduced import function which should be a reserved word from es6 on and typescript.

In index.d.ts: 

`export function import(lang: string): void;`

Waiting for a fix, as a workaround (if you still want to use 3.7.2) just rename `import` function in node_modules.

**Comment by llulani** [comment]
In addition, I'm trying to use this package in an Angular 6 app. 

With registerLocale the app is working fine, although I still have the warning as #98 [https://github.com/michaelwittig/node-i18n-iso-countries/issues/98]: 

WARNING in ./node_modules/i18n-iso-countries/index.js
46:18-63 Critical dependency: the request of a dependency is an expression

I tried to rename the `import` function (both in index.d.ts and index.js) but the app crashes with the following error ():

Uncaught Error: Cannot find module "./langs/en.json".
    at webpackEmptyContext (i18n-iso-countries sync:2)
    at Object.push../node_modules/i18n-iso-countries/index.js.exports.importLocale (index.js:46)
    at Object../src/app/app.module.ts (app.module.ts:22)
    at __webpack_require__ (bootstrap:76)
    at Object../src/main.ts (environment.ts:15)
    at __webpack_require__ (bootstrap:76)
    at Object.0 (main.ts:12)
    at __webpack_require__ (bootstrap:76)
    at checkDeferredModules (bootstrap:43)
    at Array.webpackJsonpCallback [as push] (bootstrap:30)

**Comment by michaelwittig** [comment]
Duplicate of #98 
Please use `i18n-iso-countries@3.7.3`
